// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"dash-shoes-plugin","status":true,"description":"실내화를 착용했을 때만 대시가 가능한 시스템","parameters":{"dashShoeId":"2"}},
{"name":"timer-game-over","status":true,"description":"타이머가 0이 되면 게임오버가 되는 시스템","parameters":{"gameOverMessage":"시간이 초과되었습니다!"}},
{"name":"WASDKeys","status":true,"description":"WASD 키를 방향키로 사용하도록 변경하는 플러그인","parameters":{}},
{"name":"menu","status":true,"description":"특정 키를 눌렀을 때 매뉴얼 창을 표시하는 플러그인입니다.","parameters":{"KeyCode":"77","ManualText":"-이동키 : W,A,S,D 또는 방향키\\n -상호작용 : Space 또는 Enter\\n -설정 창 : Esc"}},
{"name":"PlayerVision","status":true,"description":"플레이어 주변에 시야/안개 효과를 추가합니다.","parameters":{"visionRadius":"0","darknessDensity":"150"}},
{"name":"PlayerVisionRange","status":false,"description":"플레이어 주변에 시야/안개 효과를 추가합니다.","parameters":{"visionRadius":"4","darknessDensity":"255"}},
{"name":"RemoveGoldAndHP","status":false,"description":"메뉴에서 골드 표시와 HP/MP 바를 제거합니다.","parameters":{}},
{"name":"ExecuteOtherMapEvent","status":true,"description":"Safely execute events even after map transfers.","parameters":{}}
];
